### ISSUE TITLE
FindById is not a function

### ISSUE THREAD

**Issue by RajisteB** [Cityslick/CryptoApp#5]
I code my routes for the individual coins yet when I try to bring up the page I get ->

TypeError: Coin.findById is not a function
    at liveCryptoController.show (/Users/student_11/wdi/Projects/CryptoApp/controllers/livecrypto-controller.js:14:10)
    at Layer.handle [as handle_request] (/Users/student_11/wdi/Projects/CryptoApp/node_modules/express/lib/router/layer.js:95:5)

link to code: https://github.com/Cityslick/CryptoApp/blob/master/controllers/livecrypto-controller.js

**Comment by RajisteB** [comment]
Forgot module.exports...
